# Generated by Django 4.1.3 on 2022-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('rent', models.CharField(max_length=200)),
                ('beds', models.CharField(max_length=200)),
                ('bathrooms', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('src', models.TextField()),
                ('address', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id', 'date'],
            },
        ),
    ]
